### ISSUE TITLE
Exception from the plugin: executing git command from EDT

### ISSUE THREAD

**Issue by juliabeliaeva** [ml-in-programming/topias#8]
```
java.lang.Throwable: Synchronous execution on EDT: /usr/bin/git -c core.quotepath=false -c log.showSignature=false rev-list HEAD --count "--since=\"last month\""
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.execution.process.OSProcessHandler.checkEdtAndReadAction(OSProcessHandler.java:118)
	at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:63)
	at git4idea.commands.GitTextHandler.waitForProcess(GitTextHandler.java:145)
	at git4idea.commands.GitHandler.runInCurrentThread(GitHandler.java:383)
	at git4idea.commands.GitImplBase.doRun(GitImplBase.java:172)
	at git4idea.commands.GitImplBase.run(GitImplBase.java:148)
	at git4idea.commands.GitImplBase.runCommand(GitImplBase.java:46)
	at git4idea.commands.GitImpl.runCommand(GitImpl.java:41)
	at processing.GitCommitsProcessor.lambda$processGitHistory$5(GitCommitsProcessor.java:94)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:308)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:935)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:812)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:471)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:705)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:470)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by likeanowl** [comment]
Thanks, I'll take a look at it!

**Comment by likeanowl** [comment]
As I see, this could be related to bug in IDEA 2019.2.
https://github.com/flutter/flutter-intellij/issues/3697
https://youtrack.jetbrains.com/issue/CPP-16090
https://github.com/flutter/flutter-intellij/issues/3697

I'll add better logging (in order to get more details if this repeats) and release a new version of plugin on this or next weekend.

**Comment by juliabeliaeva** [comment]
I think the problem is that `VcsInitialization` invokes all the tasks in the EDT if they were added after the initialization is finished. Perhaps, initialization requests should only be used for initialization, and not for normal operations.

**Comment by likeanowl** [comment]
OK, thanks a lot! I'll fix this soon. :+1:
